[package]
name = "mcsc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
tonic = "*"
prost = "*"
tokio = { version = "*", features = ["full"] }
magic-crypt = "*"
rand = "*"
serde = "*"
toml = "*"
serde_derive = "*"
lazy_static = "*"
parking_lot = "*"
no-panic = "0.1.17"

[build-dependencies]
tonic-build = "*"
